version: '3.8'

services:
  backend:
    container_name: 'backend'
    build: './backend'
    ports:
    - '4242:4242'
    restart: 'on-failure'
    environment:
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: '4242'
      SERVER_SECRET_KEY: 'epinauteSecretKey'
      MONGODB_HOST: db
      MONGODB_PORT: '27017'
      MONGODB_DB: 'epinaute'
    networks:
      - 'frontend'
      - 'backend'

  db:
    container_name: 'database'
    image: 'mongo:4.4.6'
    ports:
    - '27017:27017'
    networks:
      - 'backend'
    volumes:
    - 'db-data:/data/db'

volumes:
  db-data:

networks:
  frontend:
  backend: