version: '3.8'

services:
  frontend:
   container_name: 'frontend'
   build: './frontend'
   ports:
   - '3000:80'
   restart: 'on-failure'
   environment:
      API_HOST: backend
      API_PORT: '2442'
      EMAILJS_SERVICEID: 'service_0iyrdpa'
      EMAILJS_TEMPLATEID: 'template_ulm02cs'
      EMAILJS_USERID: 'user_hIwiJ3wMrHTeu0XP0k73A'

   networks:
     - 'frontend'

  backend:
    container_name: 'backend'
    build: './backend'
    ports:
    - '2442:2442'
    restart: 'on-failure'
    environment:
      SERVER_HOST: '127.0.0.1'
      SERVER_PORT: '2442'
      SERVER_SECRET_KEY: 'epinauteSecretKey'
      MONGODB_HOST: db
      MONGODB_PORT: '27017'
      MONGODB_DB: 'epinaute'
    networks:
      - 'frontend'
      - 'backend'

  db:
    container_name: 'database'
    image: 'mongo:4.4.6'
    ports:
    - '27017'
    networks:
      - 'backend'
    volumes:
    - 'db-data:/data/db'

volumes:
  db-data:

networks:
  frontend:
  backend: